;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	c-electric-brace
	c-electric-delete-forward
	c-electric-semi&comma
	hydra--negative-argument
	indent-for-tab-command
	ivy-backward-delete-char
	org-delete-char
	org-self-insert-command
	picture-self-insert
	))

(setq mc/cmds-to-run-once
      '(
	hydra-ivy/ivy-minibuffer-shrink
	))
